name: Assume AWS Web Federation Role
description: Allows a workflow to assume an AWS IAM role using Web Federation. See [this post](https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html) for details.
inputs:
  iam_role_arn:
    description: The ARN of the IAM Role to assume.
    required: true
  aws_default_region:
    description: The name of the AWS region to use as the default one for acquired credentials.
    required: true
    default: us-east-1
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export AWS_ROLE_ARN=${{ iam_role_arn }}
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        export AWS_DEFAULT_REGION=${{ aws_default_region }}

        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      