name: Trunk workflow
on:
   push:
     branches:
       - "trunk"
     paths-ignore:
       - ".github/**"
       - "README.md"
       - "LICENSE"
permissions:
  id-token: write
  contents: read
jobs:
  release:
    name: Generate release
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Acquire AWS credentials
        uses: zarnovican/aws-oidc-login-action@v1.0.2
        with:
          role: "arn:aws:iam::068845349622:role/GHA-yardbirdsax-terraform-aws-github-action-federation-role"
          aws-region: us-east-1
          client-id: sigstore
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          terraform_wrapper: false
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run go tests
        shell: bash
        working-directory: "test/"
        run: |
          go test -v -timeout 30m -count 1 ./...       
      - name: Generate semantic version
        id: generate-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"
      - name: Create tag
        run: git tag ${{ steps.generate-version.outputs.version }} && git push --tags
      - name: Generate release
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: "${{ steps.generate-version.outputs.version_tag }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

        